### PR TITLE
Fix/nav and button style

### PR DESCRIPTION
**Pull request by maksimLobachevskiy**

### CODE REVIEW

**Comment by maksimLobachevskiy** [comment]
[Redirect user to Explore page after Sing up](https://trello.com/c/tYL7CRCd/33-redirect-user-to-explore-page-after-sing-up)

**Comment by maksimLobachevskiy** [comment]
[TWEET button style in form](https://trello.com/c/QG0svUkp/32-tweet-button-style-in-form)

**Comment by maksimLobachevskiy** [comment]
[#002 - "disableUnderline" warning in console](https://trello.com/c/JY3d7Yln/30-002-disableunderline-warning-in-console)

**Comment by maksimLobachevskiy** [comment]
[#002 - "disableUnderline" warning in console](https://trello.com/c/JY3d7Yln/30-002-disableunderline-warning-in-console)

**Review by Zeitgeist0 — APPROVED** [review]

**Pull request merged**
